services:
  redis:
    image: redis
    volumes:
      - ./redis-data:/data


  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - data:/var/lib/mysql  



  app:
    depends_on:
      - db
    build: .
    ports: 
     - 5000:5000
    volumes:
    - .:/code
    environment:
      - REDIS_HOST=redis  

  apptest:
    build: .
    command:  python -m unittest    
    
volumes:
  data:     

