name: build-push

on: [push, pull_request]
  

jobs:
    
            
                

    build-push:
        if:   github.event_name == 'push'
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3


            - name: set up/install docker
              uses: docker/setup-buildx-action@v2  
            
            - name: Login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: |
                    ithatabdullah/project:latest  
                    ithatabdullah/project:${{ github.sha }} 
                cache-from:
                        ithatabdullah/project:latest    


    test:
        if:   github.event_name == 'push' || 'pull_request' && github.ref == 'refs/heads/main'  
        
        runs-on: ubuntu-latest
        steps:
            - name: checkoutcode
              uses: actions/checkout@v3

            - name: test
              run:
                docker compose -f Docker-compose.yml run apptest                    






