name: deploy

on:
    workflow_run:
        workflows: ["build"]
        branches: [main]
        types:
        - completed
jobs:
    runner:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: self-hosted
        strategy:
            matrix:
                http: ["10.0.2.150","10.0.2.149"]
        steps:
            - name: deploying app on http server
              run: 
                ssh -i ~/ssh/capstonekey.pem root@${{matrix.http}} " cd /project && docker image pull ithatabdullah/project:latest && docker compose -f Docker-compose.yml run --no-deps -d app  && docker image prune -f -a --filter "until=168h" "


                    